### ISSUE TITLE
Document Node and npm prerequisites

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1062]
I was working on a [Wemaker Desktop](https://github.com/mozilla/webmaker-desktop) ticket today so I had my Node and npm updated according to the [prereq](https://github.com/mozilla/webmaker-desktop#prerequisites).  Now when I switched back to this Teach site repo I encountered the following errors when running `npm start`

```shell
> teach.webmaker.org@0.0.10 prestart /Users/mavisou/Development/teach.webmaker.org
> rm -rf dist


> teach.webmaker.org@0.0.10 start /Users/mavisou/Development/teach.webmaker.org
> gulp watch

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/mavisou/Development/teach.webmaker.org/node_modules/lwip/lib/Image.js:8:19
    at Object.<anonymous> (/Users/mavisou/Development/teach.webmaker.org/node_modules/lwip/lib/Image.js:471:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.12.0
npm ERR! code ELIFECYCLE
npm ERR! teach.webmaker.org@0.0.10 start: `gulp watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the teach.webmaker.org@0.0.10 start script 'gulp watch'.
npm ERR! This is most likely a problem with the teach.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls teach.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mavisou/Development/teach.webmaker.org/npm-debug.log
```

It would be helpful if we could document what the prereqs are in the README.md.

**Comment by mmmavis** [comment]
for reference, this is what solves the above error

```shell
rm -rf node_modules/
npm install
```

**Comment by toolness** [comment]
Oh, hm... based on googling it *seems* like this is actually due to changing the version of node... compiled binaries are specific to the version of node you're using, so even if we document the version of node/npm that we require (which is a good idea), I think it will still be possible to run into this error, if the user switches to any different version of node and tries to re-run the site? Not sure though...

**Comment by mmmavis** [comment]
Moving this to the first heartbeat of 2016.  Would like to check with @Pomax about whether or not we should close this ticket.
